/**
 * 產生靜態匯入檔，讓 esbuild 能打包動態載入的 commands/events
 */
const fs = require("fs");
const path = require("path");

const srcDir = path.join(__dirname, "..", "src");
const outFile = path.join(srcDir, "generated", "registry.ts");

const dirs = [
    { path: "events", exportName: "eventModules" },
    { path: "slashCommands", exportName: "slashCommandModules" },
    { path: "contextMenuCommands", exportName: "contextMenuModules" },
];

const lines = ["// Auto-generated by scripts/generate-imports.js - do not edit", ""];
const imports = [];
const eventExports = [];
const slashExports = [];
const contextExports = [];

for (const { path: dir, exportName } of dirs) {
    const fullPath = path.join(srcDir, dir);
    if (!fs.existsSync(fullPath)) continue;
    const items = fs.readdirSync(fullPath, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .filter((d) => fs.existsSync(path.join(fullPath, d.name, "index.ts")));
    for (const item of items) {
        const prefix = dir === "events" ? "evt" : dir === "slashCommands" ? "slash" : "ctx";
        const varName = `${prefix}_${item.name}`.replace(/-/g, "_");
        const importPath = `../${dir}/${item.name}`;
        imports.push(`import * as ${varName} from "${importPath}";`);
        if (exportName === "eventModules") eventExports.push(`  ${varName},`);
        else if (exportName === "slashCommandModules") slashExports.push(`  ${varName},`);
        else contextExports.push(`  ${varName},`);
    }
}

lines.push(...imports);
lines.push("");
lines.push("export const eventModules = [");
lines.push(...eventExports);
lines.push("];");
lines.push("");
lines.push("export const slashCommandModules = [");
lines.push(...slashExports);
lines.push("];");
lines.push("");
lines.push("export const contextMenuModules = [");
lines.push(...contextExports);
lines.push("];");

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"));
console.log("Generated:", outFile);
