// Auto-generated by scripts/generate-registry.js - do not edit manually

import { SlashCommandBuilder, ContextMenuCommandBuilder } from "discord.js";
import { EventMoudle } from "./type";

// Slash commands
import * as slash_addMusicBot from "./slashCommands/addMusicBot";
import * as slash_changeSeverName from "./slashCommands/changeSeverName";
import * as slash_purge from "./slashCommands/purge";

// Context menu commands
import * as context_context from "./contextMenuCommands/context";

// Events
import * as event_clientReady from "./events/clientReady";
import * as event_guildCreate from "./events/guildCreate";
import * as event_interactionCreate from "./events/interactionCreate";
import * as event_messageCreate from "./events/messageCreate";
import * as event_messageDelete from "./events/messageDelete";
import * as event_messageReactionAdd from "./events/messageReactionAdd";
import * as event_messageReactionRemove from "./events/messageReactionRemove";
import * as event_messageUpdate from "./events/messageUpdate";

export const slashCommandModules = [
  slash_addMusicBot,
  slash_changeSeverName,
  slash_purge,
];

export const contextMenuCommandModules = [
  context_context,
];

export const eventModules = [
  event_clientReady,
  event_guildCreate,
  event_interactionCreate,
  event_messageCreate,
  event_messageDelete,
  event_messageReactionAdd,
  event_messageReactionRemove,
  event_messageUpdate,
];